parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    
doctrine:
    dbal: 
        # configure these for your database server
        driver:           '%env(resolve:DBDRIVER)%'
        dbname:           '%env(resolve:DBAPPNAME)%'
        user:             '%env(resolve:DBAPPUSER)%'
        password:         '%env(resolve:DBAPPPASSWORD)%'
        host:             '%env(resolve:DBHOST)%'
        port:             '%env(resolve:DBPORT)%'
        url:              '%env(resolve:DATABASE_URL)%'
        #server_version:   '%env(resolve:DBVERSION)%'
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci


    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            PiaApi:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'PiaApi\Entity'
                alias: PiaApi
