doctrine:
    dbal:
        connections:
            default:
                charset:  UTF8
                url:      '%env(DATABASE_URL)%'
                server_version: '5.7'
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    PiaOauth:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Oauth'
                        prefix: 'PiaApi\Entity\Oauth'
                        alias: PiaOauth
                    PiaApi:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Pia'
                        prefix: 'PiaApi\Entity\Pia'
                        alias: PiaApi
                    
