fos_oauth_server:
    db_driver: orm
    client_class:        PiaApi\Entity\Oauth\Client
    access_token_class:  PiaApi\Entity\Oauth\AccessToken
    refresh_token_class: PiaApi\Entity\Oauth\RefreshToken
    auth_code_class:     PiaApi\Entity\Oauth\AuthCode
    service:
        user_provider: PiaApi\Auth\UserProvider
        storage:       PiaApi\Auth\OAuthStorage
        client_manager: PiaApi\Auth\ClientManager
