nelmio_api_doc:
    documentation:
        #host: api.test.pialab.io
        schemes: [http]
        info:
            title: Pialab API
            description: API documentation for Pialab
            version: 1.0.0-beta

    areas:
        default:
            path_patterns:
                - ^/pias
                - ^/folders
        admin:
            path_patterns:
                - ^/users
                - ^/structures
