nelmio_api_doc:
    documentation:
        #host: api.test.pialab.io
        schemes: [http]
        info:
            title: Pialab API
            description: API documentation for Pialab
            version: 1.2.4

    areas:
        default:
            path_patterns:
                - '%api_pattern%' # see services.yaml
