api_controllers:
    resource: ../../src/Controller/
    type: annotation

home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /manageUsers
        permanent: true