api_controllers:
    resource: ../../src/Controller/
    type: annotation

login:
   path: /login
   controller: PiaApi\Controller\UserController::loginAction

logout:
   path: /logout
   controller: PiaApi\Controller\UserController::logoutAction